import type { Product } from "./types";

/** Jewelry, clothing, personalised and keepsake products. */
export const culturalProducts: Product[] = [
  {
    slug: "amharic-name-necklace",
    title: "Amharic Script Name Necklace",
    tag: "Personalized Jewelry",
    summary:
      "A custom pendant with a name written in Ge'ez script, in gold-tone, silver-tone or solid metal.",
    bestFor: "Daughter · Girlfriend · Teen girl",
    budget: "under-100",
    affiliateUrl: null,
    art: { hue: 285, motif: "cross" },
    updated: "2026-08-30",
    tags: ["jewelry", "necklace", "amharic", "personalized", "script", "ge'ez", "name"],
    placements: [
      { category: "personalized-gifts", subcategory: "personalized-jewelry" },
      { category: "ethiopian-eritrean-gifts", subcategory: "ethiopian-inspired" },
      { category: "ethiopian-eritrean-gifts", subcategory: "jewelry" },
      { category: "gifts-for-her", subcategory: "daughter" },
      { category: "gifts-for-her", subcategory: "girlfriend" },
      { category: "gifts-for-her", subcategory: "teen-girl" },
      { category: "gifts-by-occasion", subcategory: "birthday" },
    ],
    guide: {
      heading: "Amharic Name Necklaces: Get the Spelling Right First",
      standfirst:
        "The most requested personalised gift in the Habesha diaspora, and the one with the highest rate of expensive, unfixable mistakes.",
      why: [
        "Ge'ez script is visually distinctive in a way Latin-alphabet name jewellery is not. Each character is a syllable with its own form, so even a short name becomes a genuinely ornamental shape rather than simply letters on a chain.",
        "It works as an everyday cultural signal. Unlike a piece that only comes out for holidays, a name pendant is worn to work and to school — which is exactly why it resonates with second-generation recipients negotiating two identities.",
        "It is personal without being presumptuous. A name is specific to the recipient but carries none of the commitment implied by other jewellery, which makes it viable for a girlfriend, a sister or a niece alike.",
      ],
      whoFor: [
        "Daughters, nieces and teenagers connecting with heritage",
        "A girlfriend or partner, where a name is personal but not loaded",
        "Anyone with a name that is commonly misspelled in Latin script",
        "Graduation and milestone birthdays, where a keepsake suits the moment",
      ],
      whyGift: [
        "Highly personal — it can only have been made for them",
        "Worn daily rather than kept in a box",
        "Reads as cultural without requiring explanation",
      ],
      considerations: [
        "Have the spelling checked by a fluent reader before ordering, ideally someone from the recipient's own family. Transliteration from Latin to Ge'ez is not one-to-one and sellers frequently guess wrong.",
        "Confirm the seller sets the script from your typed Ge'ez characters rather than converting from Latin themselves. Ask for a proof image before production.",
        "Custom pieces are usually non-returnable. Spelling errors are your problem, not the seller's.",
        "Plated pieces tarnish, particularly on anyone who wears jewellery in the shower. Solid silver costs more and lasts far longer.",
        "Thin script pendants with fine connecting strokes are structurally weak; look at the metal thickness in the photos.",
      ],
      pros: [
        "Deeply personal and visually striking",
        "Worn every day",
        "Suits a wide range of ages and relationships",
      ],
      cons: [
        "Spelling errors are permanent and non-refundable",
        "Plating wears through with daily use",
        "Delicate scripts can snap at thin points",
        "Custom production adds lead time — order early",
      ],
      alternatives: ["ethiopian-cross-pendant", "tigrinya-script-bracelet", "personalized-birthstone-ring"],
    },
  },
  {
    slug: "ethiopian-cross-pendant",
    title: "Ethiopian Cross Pendant",
    tag: "Jewelry",
    summary:
      "The interlaced Ethiopian cross in silver or gold-tone, in regional styles from Lalibela to Axum.",
    bestFor: "Christmas · Baptism · Grandma",
    budget: "under-100",
    affiliateUrl: null,
    art: { hue: 45, motif: "cross" },
    updated: "2026-07-22",
    tags: ["jewelry", "cross", "ethiopian", "orthodox", "pendant", "faith", "silver"],
    placements: [
      { category: "ethiopian-eritrean-gifts", subcategory: "jewelry" },
      { category: "ethiopian-eritrean-gifts", subcategory: "ethiopian-inspired" },
      { category: "gifts-for-her", subcategory: "grandma" },
      { category: "gifts-for-her", subcategory: "mom" },
      { category: "gifts-by-occasion", subcategory: "christmas-holidays" },
      { category: "gifts-for-him", subcategory: "son" },
    ],
    guide: {
      heading: "Choosing an Ethiopian Cross: Style, Region and Meaning",
      standfirst:
        "Not all Ethiopian crosses are the same, and the differences between them are regional and historical rather than decorative.",
      why: [
        "The interlace is the tradition. Ethiopian crosses are built from continuous woven latticework rather than two intersecting bars, a design language stretching back to the Axumite period and unlike any other Christian cross form.",
        "Regional styles are genuinely distinct. Lalibela, Axum and Gondar crosses each have recognisable geometry, and giving one from the recipient's own family region turns a nice object into a specific one.",
        "It carries meaning across generations. For Orthodox families this is a faith object first, which gives it a weight that decorative jewellery does not have — and makes it a natural baptism, Genna or Fasika gift.",
      ],
      whoFor: [
        "Orthodox Christian family members, particularly older relatives",
        "A baptism or christening, where a cross is the conventional gift",
        "Anyone who wears a cross daily and would appreciate a distinctly Habesha one",
        "Second-generation family members connecting to a specific regional heritage",
      ],
      whyGift: [
        "Meaningful rather than merely decorative",
        "Frequently kept and passed down",
        "Appropriate across a wide age range",
      ],
      considerations: [
        "Consider whether the recipient is practising. A cross is a faith object, and it is not a neutral gift for someone who is not religious.",
        "Larger hand-carved crosses are heavy on a fine chain. Buy an appropriately weighted chain or check one is included.",
        "Sellers often label all styles generically as 'Ethiopian cross'. If regional specificity matters, look at the geometry in the photographs rather than the title.",
        "Silver tarnishes and openwork interlace is difficult to polish. A rhodium finish or regular gentle cleaning helps.",
      ],
      pros: [
        "Strong cultural and religious meaning",
        "Distinctive design unlike other cross styles",
        "Long-lived, often passed down",
      ],
      cons: [
        "Not appropriate for non-religious recipients",
        "Openwork is fiddly to clean",
        "Regional style rarely stated by sellers",
      ],
      alternatives: ["amharic-name-necklace", "tigrinya-script-bracelet"],
    },
  },
  {
    slug: "tigrinya-script-bracelet",
    title: "Tigrinya Script Bracelet",
    tag: "Personalized Jewelry",
    summary:
      "A cuff or chain bracelet engraved with a word, name or phrase in Tigrinya.",
    bestFor: "Eritrean gifts · Sister · Anniversary",
    budget: "under-50",
    affiliateUrl: null,
    art: { hue: 210, motif: "arch" },
    updated: "2026-08-05",
    tags: ["jewelry", "bracelet", "tigrinya", "eritrean", "personalized", "engraved", "script"],
    placements: [
      { category: "personalized-gifts", subcategory: "personalized-jewelry" },
      { category: "ethiopian-eritrean-gifts", subcategory: "eritrean-inspired" },
      { category: "ethiopian-eritrean-gifts", subcategory: "jewelry" },
      { category: "gifts-for-her", subcategory: "sister" },
      { category: "gifts-by-occasion", subcategory: "anniversary" },
    ],
    guide: {
      heading: "Tigrinya Script Jewelry: Specifically Eritrean Gifting",
      standfirst:
        "Most 'Habesha' jewellery defaults to Amharic. For Eritrean recipients, Tigrinya script is the detail that shows you were paying attention.",
      why: [
        "The distinction matters to the recipient. Habesha is a shared umbrella, but Eritrean identity is its own thing, and a gift that defaults to Amharic for a Tigrinya-speaking family quietly misses — this is the piece that does not.",
        "Both languages use the Ge'ez script, so the same engraving process applies, but the words differ. A phrase such as a mother's name or a short blessing is written differently, and getting that right is the entire value of the gift.",
        "A bracelet suits engraving better than a pendant for longer text. A cuff gives a continuous horizontal surface, so a phrase reads naturally rather than being squeezed into a shape.",
      ],
      whoFor: [
        "Eritrean family members and partners",
        "Anyone who has noticed cultural gifts always defaulting to Ethiopian",
        "A sister or close friend, where a phrase can be an in-joke or a shared reference",
        "Anniversaries, where a date and a short phrase work well together",
      ],
      whyGift: [
        "Specific rather than generically Habesha",
        "Engraving makes it unmistakably theirs",
        "Understated enough for daily wear",
      ],
      considerations: [
        "Confirm with a Tigrinya reader, not a translation app. Machine transliteration between Tigrinya and Amharic produces text that looks plausible and reads wrongly.",
        "Ask for a proof image before the piece goes to engraving; most sellers will provide one on request.",
        "Cuff bracelets have limited size adjustment. Chain styles are the safer choice if you do not know their wrist size.",
        "Engraving depth varies. Shallow laser marks on plated metal wear away within a year or two of daily use.",
      ],
      pros: [
        "Culturally specific in a way most listings are not",
        "Good surface for longer phrases",
        "Understated and wearable daily",
      ],
      cons: [
        "Translation errors are permanent",
        "Cuffs are hard to size remotely",
        "Shallow engraving wears off on plated metal",
      ],
      alternatives: ["amharic-name-necklace", "ethiopian-cross-pendant", "personalized-birthstone-ring"],
    },
  },
  {
    slug: "personalized-birthstone-ring",
    title: "Personalized Birthstone Ring",
    tag: "Personalized Jewelry",
    summary:
      "A stacking ring set with birthstones, optionally engraved with names or a date on the inner band.",
    bestFor: "Mom · Wife · New baby",
    budget: "under-100",
    affiliateUrl: null,
    art: { hue: 330, motif: "cross" },
    updated: "2026-06-30",
    tags: ["jewelry", "ring", "birthstone", "personalized", "mom", "engraved"],
    placements: [
      { category: "personalized-gifts", subcategory: "personalized-jewelry" },
      { category: "gifts-for-her", subcategory: "mom" },
      { category: "gifts-for-her", subcategory: "wife-partner" },
      { category: "gifts-by-occasion", subcategory: "new-baby" },
      { category: "gifts-by-occasion", subcategory: "anniversary" },
    ],
    guide: {
      heading: "Birthstone Rings for Mothers: A Gift That Grows With the Family",
      standfirst:
        "A stacking birthstone ring is one of the few gifts that can be added to rather than replaced — which suits large families particularly well.",
      why: [
        "The stacking format is the feature. One band per child means the gift can be extended at the next birth or the next Mother's Day, and each addition is meaningful rather than merely another present.",
        "It sidesteps the biggest problem with gifts for mothers: they refuse anything that looks expensive or self-indulgent. A ring that represents her children is framed as being about them, which is how it gets accepted and worn.",
        "Inner-band engraving keeps the personalisation private. Names or a date inside the band mean something to the wearer without announcing itself, which suits recipients who dislike ornate jewellery.",
      ],
      whoFor: [
        "Mothers and grandmothers, particularly with several children",
        "A new-baby gift for the mother rather than the child",
        "A wife or partner at an anniversary",
        "Anyone who prefers understated jewellery to statement pieces",
      ],
      whyGift: [
        "Extendable — you can add to it in later years",
        "Personal meaning without ostentation",
        "Accepted by recipients who reject 'extravagant' gifts",
      ],
      considerations: [
        "Ring sizing is the main risk. Borrow a ring she already wears and measure it rather than guessing, and check the seller's resizing and return policy for personalised items — many will not take them back.",
        "Simulated and lab-created stones are extremely common at lower prices. That is fine, but the listing should say so plainly; be wary of any that avoid the question.",
        "Confirm the metal. Plated bands on a daily-wear ring wear through at the underside within a couple of years; sterling silver or solid gold is the durable choice.",
        "If you plan to add bands later, check the style will still be available — discontinued designs make an extendable gift unextendable.",
      ],
      pros: [
        "Can be added to over the years",
        "Personal without being showy",
        "Suits mothers who resist gifts",
      ],
      cons: [
        "Sizing is difficult to get right remotely",
        "Personalised rings are often non-returnable",
        "Stone quality and metal are inconsistently described",
      ],
      alternatives: ["amharic-name-necklace", "tigrinya-script-bracelet", "custom-family-photo-frame"],
    },
  },
  {
    slug: "netela-traditional-scarf",
    title: "Netela Traditional Scarf",
    tag: "Clothing",
    summary:
      "Handwoven white cotton with a coloured tibeb border, worn over the shoulders at church, weddings and holidays.",
    bestFor: "Mom · Grandma · Holidays",
    budget: "under-100",
    affiliateUrl: null,
    art: { hue: 350, motif: "weave" },
    updated: "2026-08-18",
    tags: ["clothing", "netela", "scarf", "tibeb", "handwoven", "traditional", "cotton"],
    placements: [
      { category: "ethiopian-eritrean-gifts", subcategory: "clothing-accessories" },
      { category: "ethiopian-eritrean-gifts", subcategory: "shared-cultural" },
      { category: "gifts-for-her", subcategory: "mom" },
      { category: "gifts-for-her", subcategory: "grandma" },
      { category: "gifts-by-occasion", subcategory: "christmas-holidays" },
      { category: "gifts-by-occasion", subcategory: "wedding" },
    ],
    guide: {
      heading: "Buying a Netela as a Gift: One Size, Many Qualities",
      standfirst:
        "The netela is the rare piece of traditional clothing you can buy for someone without knowing their size — but quality varies more than almost anything else on this site.",
      why: [
        "It fits everybody. A netela is draped rather than fitted, which removes the single biggest obstacle to gifting traditional clothing and makes it viable for a relative you have not seen in years.",
        "It is worn regularly rather than kept for one occasion. Church, weddings, funerals, Genna, Fasika and Meskel all call for one, so a good netela earns its place in a wardrobe several times a year.",
        "The tibeb border is where the craft lives. The woven coloured band is hand-done on quality pieces, and its width and intricacy are the honest indicator of what you are paying for.",
      ],
      whoFor: [
        "Mothers and grandmothers who attend church regularly",
        "Anyone whose current netela is yellowing or fraying",
        "A relative abroad who cannot buy one locally",
        "Holiday gifting, where it will be worn within weeks",
      ],
      whyGift: [
        "No sizing problem — it suits any recipient",
        "Worn several times a year, not once",
        "Quality is visible and appreciated by anyone who knows",
      ],
      considerations: [
        "Handwoven and machine-made pieces look similar in photographs and feel completely different. Handwoven cotton is softer, slightly irregular, and considerably more expensive.",
        "Thickness varies by intended use. A light shema is for warm weather; a heavier weave is for cold churches and winter.",
        "White cotton yellows over time and many pieces are hand-wash only. Check care instructions before gifting to someone who will machine-wash everything.",
        "Border width is the main price driver. A very narrow printed border on a cheap listing is the tell-tale sign of a machine-made piece.",
      ],
      pros: [
        "One size fits all recipients",
        "Genuinely used throughout the year",
        "Handwoven versions are beautiful and long-lasting",
      ],
      cons: [
        "Machine-made pieces are widely mislabelled",
        "White cotton needs careful washing",
        "Weight and weave quality hard to judge online",
      ],
      alternatives: ["habesha-textile-wall-hanging", "habesha-kemis-inspired-dress", "ethiopian-cross-pendant"],
    },
  },
  {
    slug: "habesha-kemis-inspired-dress",
    title: "Habesha Kemis-Inspired Dress",
    tag: "Clothing",
    summary:
      "A modern dress drawing on the traditional kemis silhouette and tibeb detailing, cut for everyday or event wear.",
    bestFor: "Wedding guests · Teen girl · Holidays",
    budget: "100-plus",
    affiliateUrl: null,
    art: { hue: 340, motif: "weave" },
    updated: "2026-07-15",
    tags: ["clothing", "kemis", "dress", "tibeb", "traditional", "wedding", "modern"],
    placements: [
      { category: "ethiopian-eritrean-gifts", subcategory: "clothing-accessories" },
      { category: "ethiopian-eritrean-gifts", subcategory: "ethiopian-inspired" },
      { category: "gifts-for-her", subcategory: "teen-girl" },
      { category: "gifts-for-her", subcategory: "sister" },
      { category: "gifts-by-occasion", subcategory: "wedding" },
    ],
    guide: {
      heading: "Modern Kemis-Inspired Dresses: Sizing Is the Whole Problem",
      standfirst:
        "A beautiful gift with the worst return rate in traditional clothing. Read this before you order one for someone else.",
      why: [
        "Modern cuts make the tradition wearable more often. A full traditional kemis is reserved for major occasions; a contemporary dress using the same tibeb detailing can be worn to a graduation dinner or a friend's wedding without feeling like costume.",
        "It suits younger recipients who want the cultural connection without the formality. For teenagers especially, a modern silhouette is the difference between a dress worn and a dress hung up.",
        "Tibeb detailing carries the design. Even a simple modern cut reads as unmistakably Habesha when the woven border is used at the hem, sleeves or neckline.",
      ],
      whoFor: [
        "A sister or daughter attending weddings and family events",
        "Teenagers who like the tradition but not full formal dress",
        "Anyone who has outgrown or worn out an existing kemis",
        "Wedding guests who need something appropriate but not bridal-adjacent",
      ],
      whyGift: [
        "Striking and generous as a gift",
        "Worn to real events rather than stored",
        "Bridges traditional and contemporary wardrobes",
      ],
      considerations: [
        "Sizing is the central risk and it is a serious one. Sellers frequently use their own charts, sizes run small against US and EU standards, and personalised or made-to-order pieces are usually non-returnable. Get her actual measurements rather than her usual dress size.",
        "Confirm the return policy in writing before ordering. If the answer is no returns and you are guessing at the size, buy a netela or a scarf instead.",
        "Ask whether the tibeb is woven or printed. Printed borders cost far less and look it in person, even when the photographs are flattering.",
        "Lead times for made-to-order pieces run to weeks. Ordering three days before a wedding will not work.",
        "Avoid buying this as a surprise for a body-conscious recipient. A gift card toward one she chooses herself is often the kinder gift.",
      ],
      pros: [
        "Beautiful and generous",
        "More wearable than fully traditional dress",
        "Strong cultural design language",
      ],
      cons: [
        "Sizing is genuinely hard and often non-returnable",
        "Printed tibeb is common at lower prices",
        "Long lead times on made-to-order pieces",
      ],
      alternatives: ["netela-traditional-scarf", "custom-family-reunion-shirts", "amharic-name-necklace"],
    },
  },
  {
    slug: "custom-family-photo-frame",
    title: "Custom Engraved Photo Frame",
    tag: "Photo Gifts",
    summary:
      "A wooden or metal frame engraved with a family name, date or short message, sized for a standard print.",
    bestFor: "Grandma · Grandpa · Anniversary",
    budget: "under-50",
    affiliateUrl: null,
    art: { hue: 15, motif: "arch" },
    updated: "2026-08-25",
    tags: ["photo", "frame", "engraved", "personalized", "family", "grandparents", "keepsake"],
    placements: [
      { category: "personalized-gifts", subcategory: "photo-gifts" },
      { category: "personalized-gifts", subcategory: "engraved-gifts" },
      { category: "gifts-for-her", subcategory: "grandma" },
      { category: "gifts-for-him", subcategory: "grandpa" },
      { category: "gifts-by-occasion", subcategory: "anniversary" },
      { category: "gifts-by-occasion", subcategory: "new-baby" },
    ],
    guide: {
      heading: "Photo Gifts for Family Spread Across Continents",
      standfirst:
        "For grandparents who have not seen a grandchild in person for years, a printed photograph outperforms almost anything else you could buy.",
      why: [
        "It solves a real distance problem. Photographs live on phones now, and older relatives abroad often have no physical picture of grandchildren they rarely see. A framed print is not sentimentality — it is the only copy they will actually look at daily.",
        "Engraving turns a generic object into a specific one. A family name in Ge'ez or Latin script, or a date, makes the frame itself part of the gift rather than a container for it.",
        "It is inexpensive but reads as considered, because the value is in the photograph you chose rather than the price of the frame.",
      ],
      whoFor: [
        "Grandparents living far from grandchildren",
        "New parents, where the first professional photograph is a milestone",
        "An anniversary, using a photograph from the wedding",
        "Any older relative who does not use a smartphone comfortably",
      ],
      whyGift: [
        "Emotional weight far exceeding the cost",
        "Displayed permanently in a main room",
        "The photograph makes it impossible to duplicate",
      ],
      considerations: [
        "Check the frame's print size before ordering the print, and note that phone photographs at full-frame sizes often look soft — a 5x7 from a phone picture usually looks better than a 8x10.",
        "Verify engraving character support if you want Ge'ez script. Many engravers only handle Latin characters and will silently substitute or refuse.",
        "Consider a multi-photo frame for grandparents with several grandchildren, to avoid the awkwardness of one child being framed and others not.",
        "If posting internationally, glass fronts break. Acrylic-fronted frames survive the journey far more often.",
      ],
      pros: [
        "Genuinely meaningful for distant family",
        "Low cost, high impact",
        "Personalised in two ways — engraving and photograph",
      ],
      cons: [
        "Phone photos may not print well at larger sizes",
        "Ge'ez engraving is not universally supported",
        "Glass fronts are risky to ship",
      ],
      alternatives: ["amharic-family-name-print", "personalized-coffee-mug-amharic", "personalized-birthstone-ring"],
    },
  },
  {
    slug: "amharic-family-name-print",
    title: "Amharic Family Name Print",
    tag: "Home Décor",
    summary:
      "A framed typographic print of a family name or blessing in Ge'ez script, in a modern minimal layout.",
    bestFor: "Housewarming · Wedding · Modern homes",
    budget: "under-50",
    affiliateUrl: null,
    art: { hue: 25, motif: "arch" },
    updated: "2026-07-05",
    tags: ["print", "wall art", "amharic", "personalized", "home decor", "housewarming", "typography"],
    placements: [
      { category: "personalized-gifts", subcategory: "personalized-home-decor" },
      { category: "ethiopian-eritrean-gifts", subcategory: "ethiopian-inspired" },
      { category: "gifts-by-occasion", subcategory: "housewarming" },
      { category: "gifts-by-occasion", subcategory: "wedding" },
      { category: "gifts-for-her", subcategory: "wife-partner" },
    ],
    guide: {
      heading: "Script Prints: Cultural Wall Art for a Modern Interior",
      standfirst:
        "A well-set Ge'ez typographic print is the easiest way to make a contemporary home read as Habesha without a single cliché.",
      why: [
        "Typography suits modern interiors in a way souvenirs do not. A single name or short blessing, well set with generous white space, belongs on the same wall as any other contemporary print — which means it actually gets hung.",
        "Ge'ez characters are inherently decorative. The syllabic forms carry enough visual complexity that a name alone fills a frame; no ornament is needed, and adding any usually makes it worse.",
        "It is a low-risk personalised gift. Unlike jewellery there is no sizing, unlike clothing there is no taste risk, and the price is low enough that a mistake is not costly.",
      ],
      whoFor: [
        "A couple in a new home, especially a first shared one",
        "Newlyweds, where a family name marks the household",
        "Anyone with a minimal interior who wants a cultural piece that fits",
        "Second-generation households whose parents' décor style is not their own",
      ],
      whyGift: [
        "Hangs in a shared space where everyone sees it",
        "Modern rather than souvenir-like",
        "Inexpensive but looks considered",
      ],
      considerations: [
        "Verify the Ge'ez spelling with a fluent reader before ordering — the same rule as name jewellery, and just as unforgiving.",
        "Check whether the price includes a frame. Many listings show a framed mock-up and ship the print alone.",
        "Ask about the font. Poorly digitised Ge'ez typefaces have awkward character spacing that a reader will notice immediately even if you would not.",
        "Confirm print size against the wall you have in mind. Prints photograph without scale and A4 is smaller than most people picture.",
      ],
      pros: [
        "Fits modern interiors naturally",
        "Personalised with no sizing risk",
        "Inexpensive relative to impact",
      ],
      cons: [
        "Frame often sold separately",
        "Spelling and typeface quality vary",
        "Easy to order the wrong size",
      ],
      alternatives: ["custom-family-photo-frame", "habesha-textile-wall-hanging", "personalized-coffee-mug-amharic"],
    },
  },
  {
    slug: "personalized-coffee-mug-amharic",
    title: "Personalized Amharic Coffee Mug",
    tag: "Custom Mugs",
    summary:
      "A ceramic mug printed with a name, a phrase such as 'Buna Tetu', or a family joke in Ge'ez script.",
    bestFor: "Friend · Brother · Under $25",
    budget: "under-25",
    affiliateUrl: null,
    art: { hue: 200, motif: "vessel" },
    updated: "2026-08-11",
    tags: ["mug", "personalized", "amharic", "coffee", "budget", "office", "funny"],
    placements: [
      { category: "personalized-gifts", subcategory: "custom-mugs" },
      { category: "gifts-for-him", subcategory: "friend" },
      { category: "gifts-for-him", subcategory: "brother" },
      { category: "gifts-for-her", subcategory: "friend" },
      { category: "gifts-by-occasion", subcategory: "birthday" },
      { category: "gifts-by-occasion", subcategory: "celebration" },
    ],
    guide: {
      heading: "The Custom Mug: Low Risk, Surprisingly High Hit Rate",
      standfirst:
        "It is the least ambitious gift in this catalogue and one of the most reliably used. That combination is worth taking seriously.",
      why: [
        "It gets used daily, which is a low bar that most gifts fail. A mug enters the rotation immediately and stays there, which is more than can be said for most decorative cultural objects.",
        "Ge'ez script on a mug lands well in an office. It is a small, daily, unforced cultural signal, and it reliably starts the conversation the recipient is happy to have.",
        "The low price makes humour possible. A family joke or a phrase like 'Buna Tetu' is a good gift at mug prices and a bad one at jewellery prices, so this is the right object for it.",
      ],
      whoFor: [
        "Friends, siblings and colleagues",
        "Secret Santa and budget gift exchanges",
        "Anyone who drinks coffee at a desk",
        "A first gift where you do not yet know someone's taste",
      ],
      whyGift: [
        "Used every single day",
        "Cheap enough to give freely alongside something else",
        "Works as a joke or as a genuine cultural piece",
      ],
      considerations: [
        "Check that the printing is dishwasher and microwave safe. Cheap transfers peel within months, which turns a daily-use gift into landfill.",
        "Confirm the printer supports Ge'ez characters properly. Some render them as boxes or drop the diacritics entirely, and the proof image is your only protection.",
        "Print on both sides if the design is asymmetric, or a left-handed recipient will look at a blank side.",
        "If it is a joke, make sure it is one that survives being read by their colleagues for the next three years.",
      ],
      pros: [
        "Genuinely used daily",
        "Very low cost",
        "Good vehicle for personal humour",
      ],
      cons: [
        "Cheap prints fade or peel",
        "Ge'ez character support is inconsistent",
        "Unmemorable on its own — better paired with something",
      ],
      alternatives: ["amharic-family-name-print", "custom-family-reunion-shirts", "habesha-coffee-cup-set-sini"],
    },
  },
  {
    slug: "custom-family-reunion-shirts",
    title: "Custom Family Event Shirts",
    tag: "Custom Clothing",
    summary:
      "Printed shirts for a reunion, wedding party or graduation, with a family name or event date in Ge'ez or Latin script.",
    bestFor: "Family reunions · Weddings · Group gifting",
    budget: "under-50",
    affiliateUrl: null,
    art: { hue: 340, motif: "rays" },
    updated: "2026-06-25",
    tags: ["clothing", "custom", "shirts", "family", "reunion", "group", "wedding"],
    placements: [
      { category: "personalized-gifts", subcategory: "custom-clothing" },
      { category: "gifts-by-occasion", subcategory: "celebration" },
      { category: "gifts-by-occasion", subcategory: "graduation" },
      { category: "gifts-by-occasion", subcategory: "wedding" },
      { category: "gifts-for-him", subcategory: "brother" },
    ],
    guide: {
      heading: "Custom Shirts for Family Events: Order Earlier Than You Think",
      standfirst:
        "Matching shirts are a genuinely good idea for large Habesha family events. The failure mode is never the design — it is the timeline.",
      why: [
        "They solve the photograph problem. Large family gatherings produce chaotic group photos; matching shirts make a picture that people actually keep and reprint years later.",
        "For diaspora families who gather rarely, the shirt becomes the souvenir of the trip. It outlives the event in a way that catering and decoration do not.",
        "Bulk pricing makes this one of the few gifts that gets cheaper as the family gets larger, which is the opposite of how most group gifting works.",
      ],
      whoFor: [
        "Family reunions, especially international ones",
        "Wedding parties and pre-wedding events",
        "Graduation celebrations with a large attending family",
        "Anyone organising an event rather than buying for one person",
      ],
      whyGift: [
        "Turns a gathering into a documented occasion",
        "Cheap per person at volume",
        "Kept as a memento long after the event",
      ],
      considerations: [
        "Order weeks ahead, not days. Bulk custom printing has real lead times and rush fees are steep — this is the single most common way this gift goes wrong.",
        "Collect actual sizes rather than guessing, and order a few spares in the larger sizes. Someone always turns up unexpectedly.",
        "Confirm Ge'ez script support with a proof image before the full run prints. An error multiplied by forty shirts is expensive.",
        "Choose the garment quality deliberately. The cheapest blanks shrink badly on the first wash, which defeats the point of a keepsake.",
      ],
      pros: [
        "Excellent for large gatherings",
        "Cost per person falls with volume",
        "Long-lived memento",
      ],
      cons: [
        "Long lead times and expensive rush fees",
        "Collecting sizes is genuinely tedious",
        "A design or spelling error affects every shirt",
      ],
      alternatives: ["personalized-coffee-mug-amharic", "habesha-kemis-inspired-dress", "custom-family-photo-frame"],
    },
  },
  {
    slug: "engraved-wooden-keepsake-box",
    title: "Engraved Wooden Keepsake Box",
    tag: "Engraved Gifts",
    summary:
      "A lidded wooden box engraved with a name, date or blessing — for jewellery, documents or small heirlooms.",
    bestFor: "Wedding · Graduation · Anniversary",
    budget: "under-100",
    affiliateUrl: null,
    art: { hue: 210, motif: "cross" },
    updated: "2026-08-01",
    tags: ["engraved", "wood", "keepsake", "box", "wedding", "graduation", "personalized"],
    placements: [
      { category: "personalized-gifts", subcategory: "engraved-gifts" },
      { category: "gifts-by-occasion", subcategory: "wedding" },
      { category: "gifts-by-occasion", subcategory: "graduation" },
      { category: "gifts-by-occasion", subcategory: "anniversary" },
      { category: "gifts-for-him", subcategory: "husband-partner" },
      { category: "gifts-for-her", subcategory: "daughter" },
    ],
    guide: {
      heading: "Keepsake Boxes: A Gift That Becomes About What Goes Inside It",
      standfirst:
        "The box is the least interesting part. What makes this work is that it invites the recipient to decide what deserves keeping.",
      why: [
        "It is a gift with an open ending. Unlike an object with a fixed purpose, a keepsake box becomes whatever the recipient makes it — wedding rings, letters, a grandmother's cross — and that authorship is the actual present.",
        "Engraving suits it better than almost any other object. A flat wooden lid takes a name, a date or a short blessing cleanly, without the size constraints that make jewellery engraving so fiddly.",
        "It suits milestone occasions specifically because permanence is the message. A box engraved with a wedding date is still being opened at the twentieth anniversary.",
      ],
      whoFor: [
        "Newlyweds, engraved with the wedding date",
        "Graduates, as a place for certificates and mementoes",
        "A partner at a significant anniversary",
        "Anyone inheriting family jewellery and lacking somewhere to keep it",
      ],
      whyGift: [
        "Meaning accrues over time rather than diminishing",
        "Engraving makes it unmistakably theirs",
        "Suits milestones where permanence matters",
      ],
      considerations: [
        "Check whether the interior is lined. Unlined wood scratches jewellery, which matters if that is the intended use.",
        "Solid wood ages better than veneered MDF, and the difference is obvious after a few years. Listings often describe both simply as 'wooden'.",
        "Confirm engraving character support if you want Ge'ez script, and request a proof.",
        "Hinges are the usual failure point on cheaper boxes. Look for metal hinges rather than moulded plastic in the photographs.",
      ],
      pros: [
        "Open-ended and personal",
        "Excellent engraving surface",
        "Long-lived milestone gift",
      ],
      cons: [
        "Cheap hinges fail",
        "Veneer is often sold as solid wood",
        "Unlined interiors scratch jewellery",
      ],
      alternatives: ["custom-family-photo-frame", "amharic-family-name-print", "personalized-birthstone-ring"],
    },
  },
  {
    slug: "ethiopian-childrens-book-set",
    title: "Habesha Children's Book Set",
    tag: "Kids",
    summary:
      "Illustrated books introducing Amharic or Tigrinya words, folk tales and family vocabulary for young readers.",
    bestFor: "Young girl · Young boy · New baby",
    budget: "under-50",
    affiliateUrl: null,
    art: { hue: 35, motif: "basket" },
    updated: "2026-08-22",
    tags: ["books", "kids", "children", "amharic", "tigrinya", "language", "learning"],
    placements: [
      { category: "gifts-for-her", subcategory: "young-girl" },
      { category: "gifts-for-him", subcategory: "young-boy" },
      { category: "gifts-by-occasion", subcategory: "new-baby" },
      { category: "ethiopian-eritrean-gifts", subcategory: "shared-cultural" },
      { category: "gifts-by-occasion", subcategory: "birthday" },
    ],
    guide: {
      heading: "Children's Books: The Cultural Gift That Does the Most Work",
      standfirst:
        "For diaspora families worried about language loss, a good picture book achieves more than any decorative object in this catalogue.",
      why: [
        "It addresses the actual concern. Parents raising children abroad routinely watch the language thin out by the second generation, and books are the one gift that pushes directly against that — repeated nightly, in the child's own hands.",
        "Picture books make the language low-pressure. A child who resists a lesson will happily learn twenty words from a story, and the parent reading it usually gets a refresher too.",
        "It is one of the few gifts a young child engages with rather than merely owns. Cultural objects get admired by adults; books get read to pieces.",
      ],
      whoFor: [
        "Young children in households where the language is fading",
        "New parents starting a bilingual home",
        "Grandparents wanting something to read with grandchildren",
        "Any child birthday where a toy would be one of many",
      ],
      whyGift: [
        "Genuinely educational rather than nominally cultural",
        "Engages the child directly and repeatedly",
        "Helps the parents as much as the child",
      ],
      considerations: [
        "Check the language. Amharic and Tigrinya are different languages, and 'Ethiopian' in a listing title tells you nothing about which one is inside.",
        "Look for transliteration alongside the Ge'ez script if the parents read the language but not the script — this is common in the second generation and makes the book usable rather than decorative.",
        "Match the format to the age. Board books survive toddlers; paper pages do not.",
        "Print quality varies sharply among small independent publishers. Check reviews mentioning binding, since these books get heavy use.",
      ],
      pros: [
        "Directly supports language retention",
        "Repeated use rather than one-time novelty",
        "Benefits parent and child together",
      ],
      cons: [
        "Language is often unstated in listings",
        "Binding quality is inconsistent",
        "Script-only editions exclude non-reading parents",
      ],
      alternatives: ["personalized-coffee-mug-amharic", "custom-family-photo-frame", "habesha-music-vinyl-collection"],
    },
  },
  {
    slug: "habesha-music-vinyl-collection",
    title: "Ethio-Jazz Vinyl Collection",
    tag: "Music",
    summary:
      "Reissues of the Ethio-jazz and golden-age recordings that shaped Habesha music, pressed for a turntable.",
    bestFor: "Dad · Brother · Music lovers",
    budget: "under-100",
    affiliateUrl: null,
    art: { hue: 220, motif: "rays" },
    updated: "2026-07-28",
    tags: ["music", "vinyl", "ethio-jazz", "records", "dad", "nostalgia"],
    placements: [
      { category: "gifts-for-him", subcategory: "dad" },
      { category: "gifts-for-him", subcategory: "brother" },
      { category: "gifts-for-him", subcategory: "boyfriend" },
      { category: "ethiopian-eritrean-gifts", subcategory: "shared-cultural" },
      { category: "gifts-by-occasion", subcategory: "birthday" },
    ],
    guide: {
      heading: "Ethio-Jazz on Vinyl: Buying Nostalgia That Holds Up",
      standfirst:
        "The golden-age recordings are genuinely great records, not just sentimental ones — which is why this gift works on people who do not usually want gifts.",
      why: [
        "The music has real standing. Mulatu Astatke's arrangements and the Amha and Kaifa label recordings of the late sixties and seventies are studied and sampled internationally, so this is a gift with musical weight rather than only nostalgic value.",
        "It targets a specific memory. For a father or uncle who grew up with these records, hearing them on a turntable rather than a phone speaker is a materially different experience — and one they will not arrange for themselves.",
        "Vinyl reissues are objects. The sleeve art from that era is beautiful, and the physicality is the point for a generation that owned records and then lost them to emigration.",
      ],
      whoFor: [
        "Fathers and uncles who grew up with the originals",
        "Anyone who already owns a turntable and plays it",
        "Younger listeners who found Ethio-jazz through samples or film soundtracks",
        "A milestone birthday, where nostalgia is the theme",
      ],
      whyGift: [
        "Musically substantial rather than merely sentimental",
        "Physical object with genuinely good sleeve art",
        "Hits a specific, personal memory",
      ],
      considerations: [
        "Confirm they own a working turntable. This is the entire gift and it is astonishingly easy to overlook.",
        "Reissue quality varies. Look for reputable reissue labels and check reviews for surface noise and mastering source; unlicensed pressings from poor digital transfers are common.",
        "Check the pressing region and voltage assumptions if you are also gifting equipment.",
        "If they do not have a turntable, a well-chosen streaming subscription or a CD edition delivers the music without the barrier.",
      ],
      pros: [
        "Genuinely great music, not just nostalgic",
        "Beautiful physical packaging",
        "Highly specific to the recipient's era",
      ],
      cons: [
        "Useless without a turntable",
        "Reissue quality is inconsistent",
        "Unlicensed pressings are widespread",
      ],
      alternatives: ["ethiopian-childrens-book-set", "personalized-coffee-mug-amharic", "leather-journal-engraved"],
    },
  },
  {
    slug: "leather-journal-engraved",
    title: "Engraved Leather Journal",
    tag: "Engraved Gifts",
    summary:
      "A refillable leather-bound notebook engraved with initials, a name or a short phrase.",
    bestFor: "Graduation · Teen boy · New job",
    budget: "under-50",
    affiliateUrl: null,
    art: { hue: 195, motif: "arch" },
    updated: "2026-06-12",
    tags: ["journal", "leather", "engraved", "personalized", "graduation", "writing"],
    placements: [
      { category: "personalized-gifts", subcategory: "engraved-gifts" },
      { category: "gifts-for-him", subcategory: "teen-boy" },
      { category: "gifts-for-him", subcategory: "son" },
      { category: "gifts-by-occasion", subcategory: "graduation" },
      { category: "gifts-by-occasion", subcategory: "celebration" },
    ],
    guide: {
      heading: "The Engraved Journal: A Good Gift for People Who Are Starting Something",
      standfirst:
        "Journals are a cliché for a reason, and the cliché is defensible when the recipient is at an actual beginning.",
      why: [
        "It suits transitions specifically. A journal given at a graduation or a new job is a gift about what comes next, which is why it lands better at those moments than at, say, a birthday.",
        "Refillable covers change the maths. A leather cover that takes replacement inserts is used for a decade rather than filled once and shelved, which is what separates a real gift from a desk ornament.",
        "Engraving raises the stakes usefully. An engraved cover is harder to abandon in a drawer than an anonymous notebook, and recipients report actually using them.",
      ],
      whoFor: [
        "Graduates and anyone starting a new job",
        "Teenagers, where a plain notebook would go unused",
        "Someone who already writes and is using a cheap notebook",
        "A celebration gift where you want something personal but not intimate",
      ],
      whyGift: [
        "Fits a moment of transition",
        "Refillable versions last for years",
        "Personal without being expensive",
      ],
      considerations: [
        "Refillable versus bound is the key decision. A bound journal is finished when it is full; a refillable cover is not.",
        "Check the paper weight if they use fountain pens or markers — thin paper bleeds through and makes a nice journal unusable for the person most likely to appreciate it.",
        "Genuine leather ages beautifully and bonded leather peels within a couple of years. The listing language here is deliberately slippery.",
        "For a recipient who does not write, this is a gift that quietly becomes clutter. Be honest about whether they are that person.",
      ],
      pros: [
        "Well suited to milestones and transitions",
        "Refillable versions have real longevity",
        "Modest cost for a personalised gift",
      ],
      cons: [
        "Useless for someone who does not write",
        "Bonded leather is widely mislabelled",
        "Thin paper limits which pens work",
      ],
      alternatives: ["engraved-wooden-keepsake-box", "personalized-coffee-mug-amharic", "habesha-music-vinyl-collection"],
    },
  },
];
